export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'

export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_PLAYLISTS = 'SET_PLAYLISTS'
